feat: try first to download the source archive instead of using `git` for `github.com`
This prevents anonymous fetch to be blocked especially in company networks when remote caches are down:
```
Finished `release` profile [optimized] target(s) in 41.59s
  ERROR: error running 'git fetch origin refs/heads/*:refs/remotes/origin/* refs/tags/*:refs/tags/*' while working with @rules_rs++crate+frc__github.com_JetBrains_alacritty_41b81372:
  fatal: could not read Username for 'https://github.com': No such device or address
  fatal: expected flush after ref listing
  Process exited with code 8
  Process exited with code 8 (Step: bazel.cmd fetch  (Bazel))
  Step bazel.cmd fetch  (Bazel) failed
```